/** Structured error codes for RVDE operations. */

export const RVDEErrorCode = {
  CAPABILITY_MISSING: 'CAPABILITY_MISSING',
  MODULE_NOT_FOUND: 'MODULE_NOT_FOUND',
  MODULE_INIT_FAILED: 'MODULE_INIT_FAILED',
  MODULE_ALREADY_INITIALIZED: 'MODULE_ALREADY_INITIALIZED',
  BOOT_SEQUENCE_FAILED: 'BOOT_SEQUENCE_FAILED',
  BOOT_INVALID_STATE: 'BOOT_INVALID_STATE',
  MEMORY_ALLOC_FAILED: 'MEMORY_ALLOC_FAILED',
  MEMORY_REGION_NOT_FOUND: 'MEMORY_REGION_NOT_FOUND',
  MEMORY_MAP_FAILED: 'MEMORY_MAP_FAILED',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  STORAGE_READ_FAILED: 'STORAGE_READ_FAILED',
  STORAGE_WRITE_FAILED: 'STORAGE_WRITE_FAILED',
  PROCESS_NOT_FOUND: 'PROCESS_NOT_FOUND',
  PROCESS_SPAWN_FAILED: 'PROCESS_SPAWN_FAILED',
  IPC_CHANNEL_CLOSED: 'IPC_CHANNEL_CLOSED',
  IPC_CHANNEL_NOT_FOUND: 'IPC_CHANNEL_NOT_FOUND',
  IPC_SEND_FAILED: 'IPC_SEND_FAILED',
  VFS_NOT_MOUNTED: 'VFS_NOT_MOUNTED',
  VFS_PATH_NOT_FOUND: 'VFS_PATH_NOT_FOUND',
  VFS_PERMISSION_DENIED: 'VFS_PERMISSION_DENIED',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  INVALID_ARGUMENT: 'INVALID_ARGUMENT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type RVDEErrorCode = (typeof RVDEErrorCode)[keyof typeof RVDEErrorCode];

export interface RVDEError {
  readonly code: RVDEErrorCode;
  readonly message: string;
  readonly module?: string;
  readonly cause?: unknown;
}

export function createError(
  code: RVDEErrorCode,
  message: string,
  options?: { module?: string; cause?: unknown },
): RVDEError {
  return {
    code,
    message,
    module: options?.module,
    cause: options?.cause,
  };
}
